Class {
	#name : #MTTestObjectB,
	#superclass : #Object,
	#instVars : [
		'c',
		'lint',
		'lstring',
		'lfloat'
	],
	#category : #'MoTion-Tests-class-data-tests'
}

{ #category : #accessing }
MTTestObjectB >> c: aC [

	c := aC
]

{ #category : #accessing }
MTTestObjectB >> lfloat: anObject [

	lfloat := anObject
]

{ #category : #accessing }
MTTestObjectB >> lint [

	^ lint
]

{ #category : #accessing }
MTTestObjectB >> lint: anObject [

	lint := anObject
]

{ #category : #accessing }
MTTestObjectB >> lstring: anObject [

	lstring := anObject
]
